  - name: installing mysql server
    package:
      name: mysql-server
      state: present
  - name: start and enable service
    service:
      name: mysqld
      state: started
      enabled: yes
  - name: installing python pip3.9 boto3 botocore
    ansible.builtin.pip:
      name:
       - boto3
       - botocore
      executable: pip3.9
  - name: setup root password
    command: mysql_secure_installation --set-root-pass "{{ root_password }}"